Use paint for Line vertical scrolling
golded-plus/golded-plus pull request #52
Opened 2023-10-14 04:44 UTC by shtirlic

Due to unknown reasons, paintLine does not play nice with pseudo/cyr chars, using Paint fixes this.

2023-10-14 04:46 UTC, shtirlic commented
@vitaliy-aksyonov  any ideas of the root case?

2023-10-14 04:50 UTC, vitaliy-aksyonov commented
What is your environment? Which locale do you use? I have no issues with that when run in ru_RU.KOI8_R. All pseudographics displayed correctly.

2023-10-14 04:53 UTC, shtirlic commented
```
+ CMD='/home/shtirlic/bin/golded -VV'
+ export LC_ALL=ru_RU.KOI8-R
+ LC_ALL=ru_RU.KOI8-R
+ export LANG=ru_RU.KOI8-R
+ LANG=ru_RU.KOI8-R
```
Konsole

2023-10-14 04:55 UTC, shtirlic commented
Also see this note in advanced config
```
// All pseudo-graphics symbols is replaced with ASCII symbols to
//  prevent garbage displaing of the tables & etc. This table may be used
// on Linux Xterm
;XlatCharSet CP866       KOI8-R      866_koiX.chs

```

2023-10-17 04:45 UTC, vitaliy-aksyonov commented
> Also see this note in advanced config
> 
> ```
> // All pseudo-graphics symbols is replaced with ASCII symbols to
> //  prevent garbage displaing of the tables & etc. This table may be used
> // on Linux Xterm
> ;XlatCharSet CP866       KOI8-R      866_koiX.chs
> ```
> 
> maybe you are using this?

Sorry for late reply. I don't use that conversion table and never seen such behavior. No matter if I use ssh and putty or linux console directly.
Could you please provide minimum config and steps to reproduce this issue?

2024-02-12 17:19 UTC, vitaliy-aksyonov commented
This have to be fixed by #80
Could you please test if it helps?

2024-05-22 06:53 UTC, shtirlic commented
@vitaliy-aksyonov  the same
see the pics

![image](https://github.com/golded-plus/golded-plus/assets/74080/a54495d9-c88d-4962-9be9-06eb80816474)
and after  i Hit the key down
![image](https://github.com/golded-plus/golded-plus/assets/74080/19b0d632-ce8e-4f02-b4a7-9b83c4682364)
the same with cyr text
![image](https://github.com/golded-plus/golded-plus/assets/74080/21b52aa8-1a22-468b-ba68-aaa41de61669)

```
LANG=ru_RU.KOI8-R
LC_CTYPE="ru_RU.KOI8-R"
LC_NUMERIC="ru_RU.KOI8-R"
LC_TIME="ru_RU.KOI8-R"
LC_COLLATE="ru_RU.KOI8-R"
LC_MONETARY="ru_RU.KOI8-R"
LC_MESSAGES="ru_RU.KOI8-R"
LC_PAPER="ru_RU.KOI8-R"
LC_NAME="ru_RU.KOI8-R"
LC_ADDRESS="ru_RU.KOI8-R"
LC_TELEPHONE="ru_RU.KOI8-R"
LC_MEASUREMENT="ru_RU.KOI8-R"
LC_IDENTIFICATION="ru_RU.KOI8-R"
LC_ALL=ru_RU.KOI8-R
```

```
─│┌┐└┘├┤┬┴┼▀▄█▌▐░▒▓⌠■∙√≈≤≥ ⌡°²·÷═║╒ё╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡Ё╢╣╤╥╦╧╨╩╪╫╬©юабцдефгхийклмнопярстужвьызшэщчъЮАБЦДЕФГХИЙКЛМНОПЯРСТУЖВЬЫЗШЭЩЧЪ
```

```
linux-vdso.so.1 (0x00007fbfc2623000)
libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007fbfc255c000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fbfc1e00000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007fbfc2471000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fbfc21d3000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fbfc1c14000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fbfc2625000)
```

2024-05-22 07:02 UTC, shtirlic commented
Is there any big performance benefits to paint by line and do some crazy stuff or instead just use repaint all for simplify ?

2024-05-22 15:09 UTC, vitaliy-aksyonov commented
I personally don't like fixes which doesn't fix root cause. Do you know why your change help and why original code works incorrectly?

Could you please run this code snippet on your computer and send me results?

`#include <locale>
#include <iostream>

void checks(unsigned c)
{
    std::cout << "Char: " << c <<  " isprint: " << isprint((int)c)
    << "\n iscntrl: " << iscntrl((int) c) << std::endl;
}

int main()
{
    setlocale(LC_ALL, "");
    unsigned c = 0x80;
    do
    {
        checks(c);
    } while (c++ < 0xff);
}`

All those symbols shall have isprint true and iscntrl false.

2024-05-22 15:16 UTC, vitaliy-aksyonov requested changes

2024-05-22 15:16 UTC, vitaliy-aksyonov commented on golded3/geview.cpp
> +void GMsgBodyView::PaintLine(int row, Line *line) {
Don't change code style please. Open curly brace shall be on new line.

2024-05-22 15:16 UTC, vitaliy-aksyonov commented on golded3/geview.cpp
> +        text = text.substr(0, visible_width);
substr() creates new string. erase() is more efficient. Leave it as it was.

2024-05-22 15:16 UTC, vitaliy-aksyonov commented on golded3/geview.cpp
> +    Line* dummy_index = nullptr;
This won't compile in older compilers. `nullptr` is C++11.

2024-05-22 18:24 UTC, shtirlic commented
@vitaliy-aksyonov thx, actually I think I found the issue and now researching looks like code related to window scroll and in the way how `vsave` and `vrestore` works via curses, I will update when I have some more info.

2024-05-22 18:29 UTC, vitaliy-aksyonov commented
It could be. My build uses non wide ncurses.

2024-05-22 18:32 UTC, shtirlic commented
> It could be. My build uses non wide ncurses.

Pls, could you try build with ncurses wide support  WIDE_NCURSES=1, maybe you will also encounter this bug.

2024-05-22 18:35 UTC, vitaliy-aksyonov commented
Sure. I'll try later.

2024-05-23 15:54 UTC, shtirlic commented
Closing this because root case was found and should be addressed via  #89

2024-05-23 15:54 UTC, closed without merging